// Generated by scripts/generate.ts from the token source. Do not edit.
import * as stylex from "@stylexjs/stylex";

export const focusRing = stylex.defineVars({
  "--oxy-focus-ring-width": "3px",
  "--oxy-focus-ring-offset": "2px",
  "--oxy-focus-ring-color": "var(--oxy-color-secondary)",
});

export const icon = stylex.defineVars({
  "--oxy-icon-font-family": "'Material Symbols Outlined'",
  "--oxy-icon-size": "24px",
  "--oxy-icon-fill": "0",
  "--oxy-icon-weight": "400",
  "--oxy-icon-grade": "0",
  "--oxy-icon-optical-size": "24",
});

export const button = stylex.defineVars({
  "--oxy-button-height": "40px",
  "--oxy-button-padding-inline": "var(--oxy-space-lg)",
  "--oxy-button-gap": "var(--oxy-space-sm)",
  "--oxy-button-radius": "var(--oxy-radius-full)",
  "--oxy-button-container-color": "var(--oxy-color-primary)",
  "--oxy-button-label-color": "var(--oxy-color-on-primary)",
});

export const card = stylex.defineVars({
  "--oxy-card-padding": "var(--oxy-space-lg)",
  "--oxy-card-radius": "var(--oxy-radius-md)",
  "--oxy-card-elevation": "var(--oxy-elevation-level1)",
  "--oxy-card-container-color": "var(--oxy-color-surface-container-low)",
});
