const buttonSize = (
  height: string,
  paddingInline: string,
  gap: string,
  iconSize: string,
  squareRadius: string,
  pressedRadius: string,
  innerRadius: string,
  outlineWidth: string,
) => ({
  height,
  "padding-inline": paddingInline,
  gap,
  "icon-size": iconSize,
  "square-radius": squareRadius,
  "pressed-radius": pressedRadius,
  "inner-radius": innerRadius,
  "outline-width": outlineWidth,
});

const fabSize = (
  height: string,
  iconSize: string,
  radius: string,
  paddingInline: string,
  gap: string,
) => ({
  height,
  "icon-size": iconSize,
  radius,
  "padding-inline": paddingInline,
  gap,
});

export const componentTokens = {
  "focus-ring": {
    width: "3px",
    offset: "2px",
    color: "{color.secondary}",
  },
  "touch-target": {
    size: "48px",
  },
  density: {
    step: "4px",
  },
  button: {
    xs: buttonSize(
      "32px",
      "{space.md}",
      "{space.xs}",
      "20px",
      "{radius.md}",
      "{radius.sm}",
      "{radius.xs}",
      "1px",
    ),
    sm: buttonSize(
      "40px",
      "{space.lg}",
      "{space.sm}",
      "20px",
      "{radius.md}",
      "{radius.sm}",
      "{radius.sm}",
      "1px",
    ),
    md: buttonSize(
      "56px",
      "{space.xl}",
      "{space.sm}",
      "24px",
      "{radius.lg}",
      "{radius.md}",
      "{radius.sm}",
      "1px",
    ),
    lg: buttonSize(
      "96px",
      "{space.3xl}",
      "{space.md}",
      "32px",
      "{radius.xl}",
      "{radius.lg}",
      "{radius.lg}",
      "2px",
    ),
    xl: buttonSize(
      "136px",
      "64px",
      "{space.lg}",
      "40px",
      "{radius.xl}",
      "{radius.lg}",
      "{radius.lg-increased}",
      "3px",
    ),
  },
  "button-group": {
    "connected-gap": "{space.2xs}",
    "xs-gap": "18px",
    "sm-gap": "{space.md}",
    "md-gap": "{space.sm}",
    "lg-gap": "{space.sm}",
    "xl-gap": "{space.sm}",
  },
  fab: {
    sm: fabSize("56px", "24px", "{radius.lg}", "{space.lg}", "{space.md}"),
    md: fabSize("80px", "28px", "{radius.lg-increased}", "26px", "{space.md}"),
    lg: fabSize("96px", "36px", "{radius.xl}", "28px", "{space.lg}"),
    elevation: "{elevation.level3}",
    "hovered-elevation": "{elevation.level4}",
  },
  "fab-menu": {
    "close-size": "56px",
    "item-height": "56px",
    "item-padding-inline": "{space.xl}",
    "item-gap": "{space.sm}",
    "item-icon-size": "24px",
    gap: "{space.xs}",
  },
  toolbar: {
    height: "64px",
    padding: "{space.sm}",
    gap: "{space.xs}",
    "floating-radius": "{radius.full}",
    "floating-elevation": "{elevation.level3}",
  },
  list: {
    "item-height": "56px",
    "item-padding-inline": "{space.lg}",
    "item-gap": "{space.lg}",
    "item-icon-size": "24px",
    "segmented-gap": "{space.2xs}",
    "segmented-radius": "{radius.lg}",
    "segmented-item-radius": "{radius.xs}",
    "grid-min-column-width": "160px",
    "selection-size": "18px",
    "selection-radius": "2px",
    "selection-outline-width": "2px",
  },
  menu: {
    radius: "{radius.lg}",
    padding: "{space.xs}",
    elevation: "{elevation.level2}",
    "min-width": "112px",
    "max-width": "280px",
    "item-height": "48px",
    "item-padding-inline": "{space.md}",
    "item-gap": "{space.md}",
    "item-icon-size": "20px",
    "item-radius": "{radius.xs}",
    "item-edge-radius": "{radius.md}",
    "selected-item-radius": "{radius.md}",
  },
  dropdown: {
    width: "280px",
    height: "56px",
    "padding-inline": "{space.lg}",
    gap: "{space.md}",
    "icon-size": "24px",
    radius: "{radius.xs}",
    "container-color": "{color.surface-container-highest}",
    "indicator-width": "1px",
    "focus-indicator-width": "2px",
    "label-inset": "{space.sm}",
    "supporting-gap": "{space.xs}",
  },
  chip: {
    height: "32px",
    radius: "{radius.sm}",
    "padding-inline": "{space.lg}",
    "icon-padding-inline": "{space.sm}",
    gap: "{space.sm}",
    "icon-size": "18px",
    "avatar-size": "24px",
    "outline-width": "1px",
    elevation: "{elevation.level1}",
    "hovered-elevation": "{elevation.level2}",
    "set-gap": "{space.sm}",
  },
  card: {
    padding: "{space.lg}",
    radius: "{radius.md}",
    elevation: "{elevation.level1}",
    "container-color": "{color.surface-container-low}",
  },
};
