const buttonSize = (
  height: string,
  paddingInline: string,
  gap: string,
  iconSize: string,
  squareRadius: string,
  pressedRadius: string,
  innerRadius: string,
  outlineWidth: string,
) => ({
  height,
  "padding-inline": paddingInline,
  gap,
  "icon-size": iconSize,
  "square-radius": squareRadius,
  "pressed-radius": pressedRadius,
  "inner-radius": innerRadius,
  "outline-width": outlineWidth,
});

const sliderSize = (trackHeight: string, handleHeight: string, trackRadius: string) => ({
  "track-height": trackHeight,
  "handle-height": handleHeight,
  "track-radius": trackRadius,
});

const fabSize = (
  height: string,
  iconSize: string,
  radius: string,
  paddingInline: string,
  gap: string,
) => ({
  height,
  "icon-size": iconSize,
  radius,
  "padding-inline": paddingInline,
  gap,
});

export const componentTokens = {
  "focus-ring": {
    width: "3px",
    offset: "2px",
    color: "{color.secondary}",
  },
  "touch-target": {
    size: "48px",
  },
  density: {
    step: "4px",
  },
  button: {
    xs: buttonSize(
      "32px",
      "{space.md}",
      "{space.xs}",
      "20px",
      "{radius.md}",
      "{radius.sm}",
      "{radius.xs}",
      "1px",
    ),
    sm: buttonSize(
      "40px",
      "{space.lg}",
      "{space.sm}",
      "20px",
      "{radius.md}",
      "{radius.sm}",
      "{radius.sm}",
      "1px",
    ),
    md: buttonSize(
      "56px",
      "{space.xl}",
      "{space.sm}",
      "24px",
      "{radius.lg}",
      "{radius.md}",
      "{radius.sm}",
      "1px",
    ),
    lg: buttonSize(
      "96px",
      "{space.3xl}",
      "{space.md}",
      "32px",
      "{radius.xl}",
      "{radius.lg}",
      "{radius.lg}",
      "2px",
    ),
    xl: buttonSize(
      "136px",
      "64px",
      "{space.lg}",
      "40px",
      "{radius.xl}",
      "{radius.lg}",
      "{radius.lg-increased}",
      "3px",
    ),
  },
  "button-group": {
    "connected-gap": "{space.2xs}",
    "xs-gap": "18px",
    "sm-gap": "{space.md}",
    "md-gap": "{space.sm}",
    "lg-gap": "{space.sm}",
    "xl-gap": "{space.sm}",
  },
  fab: {
    sm: fabSize("56px", "24px", "{radius.lg}", "{space.lg}", "{space.md}"),
    md: fabSize("80px", "28px", "{radius.lg-increased}", "26px", "{space.md}"),
    lg: fabSize("96px", "36px", "{radius.xl}", "28px", "{space.lg}"),
    elevation: "{elevation.level3}",
    "hovered-elevation": "{elevation.level4}",
  },
  "fab-menu": {
    "close-size": "56px",
    "item-height": "56px",
    "item-padding-inline": "{space.xl}",
    "item-gap": "{space.sm}",
    "item-icon-size": "24px",
    gap: "{space.xs}",
  },
  toolbar: {
    height: "64px",
    padding: "{space.sm}",
    gap: "{space.xs}",
    "floating-radius": "{radius.full}",
    "floating-elevation": "{elevation.level3}",
  },
  separator: {
    thickness: "1px",
    inset: "{space.lg}",
  },
  breadcrumbs: {
    gap: "{space.xs}",
    "separator-size": "18px",
  },
  tabs: {
    height: "48px",
    "icon-height": "64px",
    "padding-inline": "{space.lg}",
    "stacked-gap": "{space.2xs}",
    "inline-gap": "{space.sm}",
    "icon-size": "24px",
    "divider-width": "1px",
    "primary-indicator-thickness": "3px",
    "primary-indicator-min-length": "24px",
    "secondary-indicator-thickness": "2px",
    "scrollable-inset": "52px",
    "panel-shift": "30px",
  },
  disclosure: {
    height: "56px",
    "padding-inline": "{space.lg}",
    gap: "{space.lg}",
    "indicator-size": "24px",
    radius: "{radius.lg}",
    "segment-radius": "{radius.xs}",
    "outline-width": "1px",
    "group-gap": "{space.sm}",
    "segmented-gap": "{space.2xs}",
  },
  "navigation-item": {
    "indicator-width": "56px",
    "indicator-height": "32px",
    "horizontal-indicator-height": "40px",
    "icon-size": "24px",
    "label-gap": "{space.xs}",
    "horizontal-gap": "{space.xs}",
    "horizontal-padding-inline": "{space.lg}",
    "badge-size": "16px",
    "badge-dot-size": "6px",
  },
  "navigation-bar": {
    height: "64px",
    "horizontal-gap": "{space.sm}",
    "container-color": "{color.surface-container}",
  },
  "navigation-rail": {
    width: "96px",
    "expanded-width": "220px",
    "padding-block": "{space.2xl}",
    "item-gap": "{space.xs}",
    "item-height": "64px",
    "expanded-item-height": "56px",
    "expanded-padding-inline": "20px",
    "container-color": "{color.surface}",
  },
  "navigation-drawer": {
    width: "360px",
    padding: "{space.md}",
    radius: "{radius.lg}",
    "item-height": "56px",
    "item-gap": "{space.md}",
    "item-padding-inline-end": "{space.xl}",
    "headline-padding-inline": "{space.lg}",
    "container-color": "{color.surface-container-low}",
    elevation: "{elevation.level1}",
  },
  "app-bar": {
    "small-height": "64px",
    "medium-height": "112px",
    "large-height": "120px",
    "padding-inline": "{space.xs}",
    "title-padding-inline": "{space.lg}",
    "medium-padding-block-end": "{space.md}",
    "large-padding-block-end": "{space.md}",
    "scrolled-color": "{color.surface-container}",
  },
  "text-field": {
    height: "56px",
    "padding-inline": "{space.lg}",
    gap: "{space.md}",
    "icon-size": "24px",
    radius: "{radius.xs}",
    "container-color": "{color.surface-container-highest}",
    "indicator-width": "1px",
    "focus-indicator-width": "2px",
    "label-inset": "{space.sm}",
    "supporting-gap": "{space.xs}",
  },
  "search-field": {
    height: "56px",
    radius: "{radius.full}",
    "container-color": "{color.surface-container-high}",
  },
  checkbox: {
    size: "18px",
    radius: "2px",
    "outline-width": "2px",
    "state-layer-size": "40px",
  },
  radio: {
    size: "20px",
    "dot-size": "10px",
    "outline-width": "2px",
    "state-layer-size": "40px",
  },
  switch: {
    "track-width": "52px",
    "track-height": "32px",
    "outline-width": "2px",
    "handle-size": "16px",
    "selected-handle-size": "24px",
    "pressed-handle-size": "28px",
    "icon-size": "16px",
    "state-layer-size": "40px",
  },
  slider: {
    xs: sliderSize("16px", "44px", "{radius.sm}"),
    sm: sliderSize("24px", "44px", "{radius.sm}"),
    md: sliderSize("40px", "52px", "{radius.md}"),
    lg: sliderSize("56px", "68px", "{radius.lg}"),
    xl: sliderSize("96px", "108px", "{radius.xl}"),
    "handle-width": "4px",
    "handle-gap": "6px",
    "inner-radius": "2px",
    "stop-size": "4px",
    "value-indicator-height": "44px",
    "vertical-length": "200px",
  },
  progress: {
    "track-height": "4px",
    gap: "4px",
    "stop-size": "4px",
    "wave-amplitude": "3px",
    "wave-length": "40px",
    "circular-size": "40px",
    "circular-track-width": "4px",
    "loading-size": "48px",
    "loading-indicator-size": "38px",
  },
  "drop-zone": {
    padding: "{space.xl}",
    radius: "{radius.lg}",
    "outline-width": "1px",
  },
  list: {
    "item-height": "56px",
    "item-padding-inline": "{space.lg}",
    "item-gap": "{space.lg}",
    "item-icon-size": "24px",
    "segmented-gap": "{space.2xs}",
    "segmented-radius": "{radius.lg}",
    "segmented-item-radius": "{radius.xs}",
    "grid-min-column-width": "160px",
    "selection-size": "18px",
    "selection-radius": "2px",
    "selection-outline-width": "2px",
  },
  menu: {
    radius: "{radius.lg}",
    padding: "{space.xs}",
    elevation: "{elevation.level2}",
    "min-width": "112px",
    "max-width": "280px",
    "item-height": "48px",
    "item-padding-inline": "{space.md}",
    "item-gap": "{space.md}",
    "item-icon-size": "20px",
    "item-radius": "{radius.xs}",
    "item-edge-radius": "{radius.md}",
    "selected-item-radius": "{radius.md}",
  },
  dropdown: {
    width: "280px",
    height: "56px",
    "padding-inline": "{space.lg}",
    gap: "{space.md}",
    "icon-size": "24px",
    radius: "{radius.xs}",
    "container-color": "{color.surface-container-highest}",
    "indicator-width": "1px",
    "focus-indicator-width": "2px",
    "label-inset": "{space.sm}",
    "supporting-gap": "{space.xs}",
  },
  chip: {
    height: "32px",
    radius: "{radius.sm}",
    "padding-inline": "{space.lg}",
    "icon-padding-inline": "{space.sm}",
    gap: "{space.sm}",
    "icon-size": "18px",
    "avatar-size": "24px",
    "outline-width": "1px",
    elevation: "{elevation.level1}",
    "hovered-elevation": "{elevation.level2}",
    "set-gap": "{space.sm}",
  },
  card: {
    padding: "{space.lg}",
    radius: "{radius.md}",
    elevation: "{elevation.level1}",
    "container-color": "{color.surface-container-low}",
  },
};
