import { componentTokens } from "./component.ts";
import { semanticTokens } from "./semantic.ts";
import { tokenEntries, type TokenTree } from "./tree.ts";

const printWidth = 100;

const reservedWords = new Set(
  `break case catch class const continue debugger default delete do else enum export extends
   false finally for function if import in instanceof new null return super switch this throw
   true try typeof var void while with yield let static implements interface package private
   protected public await`.split(/\s+/),
);

const camelCase = (name: string) => name.replace(/-(\w)/g, (_, char: string) => char.toUpperCase());

const identifierOf = (group: string) => {
  const name = camelCase(group);
  return reservedWords.has(name) ? `${name}Tokens` : name;
};

function stylexModule(groups: TokenTree) {
  const declarations = Object.entries(groups).map(([group, tree]) => {
    const vars = tokenEntries({ [group]: tree })
      .map(({ cssVar, value }) => {
        const line = `  "${cssVar}": ${JSON.stringify(value)},`;
        return line.length > printWidth ? `  "${cssVar}":\n    ${JSON.stringify(value)},` : line;
      })
      .join("\n");
    return `export const ${identifierOf(group)} = stylex.defineVars({\n${vars}\n});\n`;
  });
  return [
    "// Generated by scripts/generate.ts from the token source. Do not edit.",
    'import * as stylex from "@stylexjs/stylex";\n',
    declarations.join("\n"),
  ].join("\n");
}

export const stylexModules = () => ({
  "semantic.stylex.ts": stylexModule(semanticTokens),
  "component.stylex.ts": stylexModule(componentTokens),
});
