import { readFile } from "node:fs/promises";
import { createRequire } from "node:module";
import { create, type Font } from "fontkit";
import { format } from "vite-plus/fmt";
import { fontPath } from "./font.ts";

export const directionalSymbols = new Set([
  "arrow_back",
  "arrow_back_2",
  "arrow_back_ios",
  "arrow_back_ios_new",
  "arrow_circle_left",
  "arrow_circle_right",
  "arrow_forward",
  "arrow_forward_ios",
  "arrow_left",
  "arrow_left_alt",
  "arrow_menu_close",
  "arrow_menu_open",
  "arrow_right",
  "arrow_right_alt",
  "backspace",
  "call_made",
  "call_merge",
  "call_missed",
  "call_missed_outgoing",
  "call_received",
  "call_split",
  "chevron_backward",
  "chevron_forward",
  "chevron_left",
  "chevron_right",
  "dock_to_left",
  "dock_to_right",
  "double_arrow",
  "exit_to_app",
  "expand_circle_right",
  "first_page",
  "format_indent_decrease",
  "format_indent_increase",
  "format_list_bulleted",
  "forward",
  "forward_to_inbox",
  "input",
  "keyboard_arrow_left",
  "keyboard_arrow_right",
  "keyboard_backspace",
  "keyboard_double_arrow_left",
  "keyboard_double_arrow_right",
  "keyboard_return",
  "keyboard_tab",
  "label",
  "label_important",
  "last_page",
  "left_panel_close",
  "left_panel_open",
  "list",
  "login",
  "logout",
  "menu_open",
  "notes",
  "open_in_new",
  "output",
  "playlist_add",
  "playlist_play",
  "queue_music",
  "read_more",
  "redo",
  "reply",
  "reply_all",
  "right_panel_close",
  "right_panel_open",
  "schedule_send",
  "segment",
  "send",
  "short_text",
  "sort",
  "start",
  "subdirectory_arrow_left",
  "subdirectory_arrow_right",
  "text_select_move_back_character",
  "text_select_move_back_word",
  "text_select_move_forward_character",
  "text_select_move_forward_word",
  "toc",
  "trending_down",
  "trending_flat",
  "trending_up",
  "undo",
  "wrap_text",
]);

const reservedWords = new Set(
  "arguments await break case catch class const continue debugger default delete do else enum eval export extends false finally for function if implements import in instanceof interface let new null package private protected public return static super switch this throw true try typeof var void while with yield".split(
    " ",
  ),
);

export function exportName(symbol: string) {
  const name = symbol.replace(/_(\w)/g, (_, char: string) => char.toUpperCase());
  if (/^\d/.test(name)) return `_${name}`;
  return reservedWords.has(name) ? `${name}_` : name;
}

const privateUseArea = (codepoint: number) => codepoint >= 0xe000;

function iconCodepoints(font: Font) {
  const codepoints = new Map<number, number>();
  for (const codepoint of font.characterSet.filter(privateUseArea).toSorted((a, b) => a - b)) {
    const { id } = font.glyphForCodePoint(codepoint);
    if (!codepoints.has(id)) codepoints.set(id, codepoint);
  }
  return (name: string) => {
    const glyphs = font.layout(name).glyphs;
    const codepoint = glyphs.length === 1 && glyphs[0] && codepoints.get(glyphs[0].id);
    if (!codepoint) throw new Error(`Material Symbols font has no glyph for ${name}`);
    return codepoint;
  };
}

export async function symbolNames() {
  const types = createRequire(import.meta.url).resolve("material-symbols/index.d.ts");
  return Array.from((await readFile(types, "utf8")).matchAll(/^\s+"(\w+)",?$/gm), ([, name]) =>
    String(name),
  );
}

export async function symbolsModule() {
  const font = create(await readFile(fontPath("outlined"))) as Font;
  const codepointOf = iconCodepoints(font);
  const exported = new Set<string>();
  const declarations = (await symbolNames()).map((name) => {
    const binding = exportName(name);
    if (exported.has(binding)) throw new Error(`Duplicate export ${binding} for ${name}`);
    exported.add(binding);
    const mirror = directionalSymbols.has(name) ? ", mirrorInRtl: true" : "";
    const codepoint = `0x${codepointOf(name).toString(16)}`;
    return `export const ${binding}: MaterialSymbol = { name: "${name}", codepoint: ${codepoint}${mirror} };`;
  });

  const source = [
    "// Generated by scripts/generate.ts from the material-symbols font. Do not edit.",
    'import type { MaterialSymbol } from "./symbol.ts";',
    declarations.join("\n"),
  ].join("\n\n");

  const { code, errors } = await format("symbols.ts", source);
  if (errors.length) throw new Error(`Cannot format symbols.ts: ${errors[0]?.message}`);
  return code;
}
