import { cssVar, tokens } from "@oxy/tokens";
import { format } from "vite-plus/fmt";
import { motionAllowedVar, motionEnabledVar, reducedMotionQuery } from "./preference.ts";
import { springFamilies, springSpeeds, springVar, springVars } from "./spring.ts";

const camelCase = (name: string) => name.replace(/-(\w)/g, (_, char: string) => char.toUpperCase());

const scaled = (duration: string) =>
  `calc(${duration} * var(${motionEnabledVar}) * var(${motionAllowedVar}))`;

const springConsts = (part: "duration" | "easing", wrap: (value: string) => string) =>
  springFamilies.flatMap((family) =>
    springSpeeds.map((speed) => [
      camelCase(`${family}-${speed}`),
      wrap(`var(${springVar(family, speed, part)})`),
    ]),
  );

export const motionAllowed = { default: "1", reduced: "0" };

export async function stylexModule() {
  const { duration, easing } = tokens.motion;
  const durations = Object.fromEntries([
    ...Object.keys(duration).map((step) => [
      camelCase(step),
      scaled(`var(${cssVar(`motion.duration.${step}`)})`),
    ]),
    ...springConsts("duration", scaled),
  ]);
  const easings = Object.fromEntries([
    ...Object.keys(easing).map((curve) => [
      camelCase(curve),
      `var(${cssVar(`motion.easing.${curve}`)})`,
    ]),
    ...springConsts("easing", (value) => value),
  ]);
  const preference = {
    [motionAllowedVar]: {
      default: motionAllowed.default,
      [`@media ${reducedMotionQuery}`]: motionAllowed.reduced,
    },
  };

  const source = [
    "// Generated by scripts/generate.ts from the motion tokens. Do not edit.",
    'import * as stylex from "@stylexjs/stylex";',
    `export const motionPreference = stylex.defineVars(${JSON.stringify(preference)});`,
    `export const springCurves = stylex.defineVars(${JSON.stringify(springVars())});`,
    `export const duration = stylex.defineConsts(${JSON.stringify(durations)});`,
    `export const easing = stylex.defineConsts(${JSON.stringify(easings)});`,
  ].join("\n\n");

  const { code, errors } = await format("motion.stylex.ts", source);
  if (errors.length) throw new Error(`Cannot format motion.stylex.ts: ${errors[0]?.message}`);
  return code;
}
