// Generated by scripts/generate.ts from the motion tokens. Do not edit.

import * as stylex from "@stylexjs/stylex";

export const motionPreference = stylex.defineVars({
  "--oxy-motion-allowed": { default: "1", "@media (prefers-reduced-motion: reduce)": "0" },
});

export const springCurves = stylex.defineVars({
  "--oxy-motion-spring-spatial-fast-duration": "230ms",
  "--oxy-motion-spring-spatial-fast-easing":
    "linear(0, 0.0559, 0.1793, 0.3248, 0.467, 0.5931, 0.6983, 0.7824, 0.8471, 0.8955, 0.9307, 0.9557, 0.9728, 0.9843, 0.9918, 0.9964, 0.9991, 1.0006, 1.0013, 1.0015, 1.0015, 1.0013, 1.0011, 1)",
  "--oxy-motion-spring-spatial-default-duration": "325ms",
  "--oxy-motion-spring-spatial-default-easing":
    "linear(0, 0.029, 0.0995, 0.1922, 0.2936, 0.3952, 0.4913, 0.5788, 0.6563, 0.7233, 0.7801, 0.8275, 0.8665, 0.898, 0.9233, 0.9432, 0.9587, 0.9707, 0.9797, 0.9865, 0.9914, 0.995, 0.9975, 0.9992, 1.0003, 1.001, 1.0013, 1.0015, 1.0015, 1.0014, 1.0013, 1.0012, 1.001, 1)",
  "--oxy-motion-spring-spatial-slow-duration": "496ms",
  "--oxy-motion-spring-spatial-slow-easing":
    "linear(0, 0.0133, 0.0482, 0.0979, 0.1572, 0.2221, 0.2895, 0.357, 0.4228, 0.4857, 0.545, 0.6, 0.6505, 0.6964, 0.7378, 0.7749, 0.8078, 0.8368, 0.8622, 0.8843, 0.9035, 0.9201, 0.9342, 0.9463, 0.9565, 0.9651, 0.9723, 0.9783, 0.9832, 0.9873, 0.9906, 0.9932, 0.9953, 0.997, 0.9983, 0.9993, 1.0001, 1.0006, 1.001, 1.0013, 1.0014, 1.0015, 1.0015, 1.0015, 1.0014, 1.0014, 1.0013, 1.0012, 1.0011, 1.001, 1)",
  "--oxy-motion-spring-effects-fast-duration": "150ms",
  "--oxy-motion-spring-effects-fast-easing":
    "linear(0, 0.1147, 0.3214, 0.5172, 0.6718, 0.7837, 0.8606, 0.9117, 0.9448, 0.9658, 0.979, 0.9872, 0.9923, 0.9954, 0.9972, 0.9983, 1)",
  "--oxy-motion-spring-effects-default-duration": "231ms",
  "--oxy-motion-spring-effects-default-easing":
    "linear(0, 0.0576, 0.1805, 0.3211, 0.4555, 0.5733, 0.6714, 0.7504, 0.8125, 0.8604, 0.8968, 0.9242, 0.9446, 0.9597, 0.9708, 0.979, 0.9849, 0.9892, 0.9922, 0.9945, 0.9961, 0.9972, 0.998, 0.9986, 1)",
  "--oxy-motion-spring-effects-slow-duration": "327ms",
  "--oxy-motion-spring-effects-slow-easing":
    "linear(0, 0.0327, 0.1091, 0.2059, 0.3087, 0.4086, 0.501, 0.5836, 0.6556, 0.7173, 0.7694, 0.8129, 0.8489, 0.8785, 0.9027, 0.9223, 0.9381, 0.9508, 0.9611, 0.9692, 0.9757, 0.9809, 0.985, 0.9882, 0.9907, 0.9927, 0.9943, 0.9956, 0.9965, 0.9973, 0.9979, 0.9984, 0.9987, 1)",
});

export const duration = stylex.defineConsts({
  short1:
    "calc(var(--oxy-motion-duration-short1) * var(--oxy-motion-enabled) * var(--oxy-motion-allowed))",
  short2:
    "calc(var(--oxy-motion-duration-short2) * var(--oxy-motion-enabled) * var(--oxy-motion-allowed))",
  short3:
    "calc(var(--oxy-motion-duration-short3) * var(--oxy-motion-enabled) * var(--oxy-motion-allowed))",
  short4:
    "calc(var(--oxy-motion-duration-short4) * var(--oxy-motion-enabled) * var(--oxy-motion-allowed))",
  medium1:
    "calc(var(--oxy-motion-duration-medium1) * var(--oxy-motion-enabled) * var(--oxy-motion-allowed))",
  medium2:
    "calc(var(--oxy-motion-duration-medium2) * var(--oxy-motion-enabled) * var(--oxy-motion-allowed))",
  medium3:
    "calc(var(--oxy-motion-duration-medium3) * var(--oxy-motion-enabled) * var(--oxy-motion-allowed))",
  medium4:
    "calc(var(--oxy-motion-duration-medium4) * var(--oxy-motion-enabled) * var(--oxy-motion-allowed))",
  long1:
    "calc(var(--oxy-motion-duration-long1) * var(--oxy-motion-enabled) * var(--oxy-motion-allowed))",
  long2:
    "calc(var(--oxy-motion-duration-long2) * var(--oxy-motion-enabled) * var(--oxy-motion-allowed))",
  long3:
    "calc(var(--oxy-motion-duration-long3) * var(--oxy-motion-enabled) * var(--oxy-motion-allowed))",
  long4:
    "calc(var(--oxy-motion-duration-long4) * var(--oxy-motion-enabled) * var(--oxy-motion-allowed))",
  extraLong1:
    "calc(var(--oxy-motion-duration-extra-long1) * var(--oxy-motion-enabled) * var(--oxy-motion-allowed))",
  extraLong2:
    "calc(var(--oxy-motion-duration-extra-long2) * var(--oxy-motion-enabled) * var(--oxy-motion-allowed))",
  extraLong3:
    "calc(var(--oxy-motion-duration-extra-long3) * var(--oxy-motion-enabled) * var(--oxy-motion-allowed))",
  extraLong4:
    "calc(var(--oxy-motion-duration-extra-long4) * var(--oxy-motion-enabled) * var(--oxy-motion-allowed))",
  spatialFast:
    "calc(var(--oxy-motion-spring-spatial-fast-duration) * var(--oxy-motion-enabled) * var(--oxy-motion-allowed))",
  spatialDefault:
    "calc(var(--oxy-motion-spring-spatial-default-duration) * var(--oxy-motion-enabled) * var(--oxy-motion-allowed))",
  spatialSlow:
    "calc(var(--oxy-motion-spring-spatial-slow-duration) * var(--oxy-motion-enabled) * var(--oxy-motion-allowed))",
  effectsFast:
    "calc(var(--oxy-motion-spring-effects-fast-duration) * var(--oxy-motion-enabled) * var(--oxy-motion-allowed))",
  effectsDefault:
    "calc(var(--oxy-motion-spring-effects-default-duration) * var(--oxy-motion-enabled) * var(--oxy-motion-allowed))",
  effectsSlow:
    "calc(var(--oxy-motion-spring-effects-slow-duration) * var(--oxy-motion-enabled) * var(--oxy-motion-allowed))",
});

export const easing = stylex.defineConsts({
  standard: "var(--oxy-motion-easing-standard)",
  standardAccelerate: "var(--oxy-motion-easing-standard-accelerate)",
  standardDecelerate: "var(--oxy-motion-easing-standard-decelerate)",
  emphasized: "var(--oxy-motion-easing-emphasized)",
  emphasizedAccelerate: "var(--oxy-motion-easing-emphasized-accelerate)",
  emphasizedDecelerate: "var(--oxy-motion-easing-emphasized-decelerate)",
  spatialFast: "var(--oxy-motion-spring-spatial-fast-easing)",
  spatialDefault: "var(--oxy-motion-spring-spatial-default-easing)",
  spatialSlow: "var(--oxy-motion-spring-spatial-slow-easing)",
  effectsFast: "var(--oxy-motion-spring-effects-fast-easing)",
  effectsDefault: "var(--oxy-motion-spring-effects-default-easing)",
  effectsSlow: "var(--oxy-motion-spring-effects-slow-easing)",
});
